# Generated by Django 4.1.7 on 2023-05-01 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('idtlit', '0021_alter_issue_options'),
        ('app_appeal', '0020_alter_appellate_order_details_admitted_tax'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tribunal_Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('Pre-Deposit', 'Pre-Deposit'), ('Admitted_Tax', 'Admitted_Tax'), ('DRC-03', 'DRC-03'), ('Interest', 'Interest'), ('Penalty', 'Penalty')], max_length=50)),
                ('challan_no', models.CharField(max_length=50)),
                ('challan_date', models.DateField()),
                ('tax', models.PositiveIntegerField(default=0)),
                ('interest', models.PositiveIntegerField(default=0)),
                ('penalty', models.PositiveIntegerField(default=0)),
                ('upload', models.FileField(upload_to='')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Created On')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Update On')),
                ('app_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_appeal.appellate_order')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idtlit.order')),
            ],
        ),
        migrations.CreateModel(
            name='Tribunal_Order_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demand', models.PositiveIntegerField(default=0)),
                ('disputed_tax', models.PositiveIntegerField(default=0, verbose_name='Balance Disputed Tax')),
                ('admitted_tax', models.PositiveIntegerField(default=0, verbose_name='Balance Disputed Tax')),
                ('is_disputed', models.BooleanField(default=False)),
                ('is_remanded', models.BooleanField(default=False)),
                ('reason', models.TextField(default='Pls give reason of demand', max_length=200, verbose_name='Reason for Demand')),
                ('is_recommended', models.BooleanField(default=False)),
                ('reco_reason', models.CharField(default='Write recommendation reason here', max_length=100)),
                ('is_approved', models.BooleanField(default=False)),
                ('approval_reason', models.CharField(default='Pls. write approval reason here ', max_length=100)),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Created On')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Update On')),
                ('app_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_appeal.appellate_order')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idtlit.issue')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idtlit.order')),
            ],
            options={
                'ordering': ['issue'],
            },
        ),
        migrations.CreateModel(
            name='Tribunal_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(help_text='Pls Enter Order No', max_length=50)),
                ('order_date', models.DateField()),
                ('order_gist', models.TextField(help_text='Pls enter summary of order', max_length=300)),
                ('demand', models.PositiveIntegerField(verbose_name='Impugned balance demand')),
                ('outcome', models.CharField(choices=[('Allowed', 'Allowed'), ('Rejected', 'Rejected'), ('Partly_Allowed', 'Partly Allowed'), ('Remand Back', 'Remand Back')], max_length=50)),
                ('next_appeal_by_date', models.DateField(verbose_name='2nd appeal limitation Date')),
                ('upload', models.FileField(help_text='Pls upload Copy of Order', upload_to='')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Created On')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Update On')),
                ('app_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_appeal.appellate_order')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idtlit.order')),
            ],
        ),
        migrations.CreateModel(
            name='Tribunal_Hearing_Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_no', models.CharField(max_length=50)),
                ('notice_date', models.DateField()),
                ('hearing_date', models.DateField()),
                ('upload', models.FileField(upload_to='')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Created On')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Update On')),
                ('app_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_appeal.appellate_order')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idtlit.order')),
            ],
        ),
        migrations.CreateModel(
            name='Tribunal_Appeal_Hearing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hearing_date', models.DateField()),
                ('was_effective', models.BooleanField(default=False, help_text='Pls upload copy of adjounment letter if not effective')),
                ('hearing_gist', models.TextField(blank=True, help_text='Pls Enter Brief of hearing', max_length=200)),
                ('is_complete', models.BooleanField(default=False)),
                ('next_date', models.DateField(blank=True, help_text='Pls. enter next date if hearing in not complete', null=True)),
                ('upload', models.FileField(blank=True, help_text='Pls upload as filed written submission,if filed', null=True, upload_to='')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Created On')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Update On')),
                ('app_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_appeal.appellate_order')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idtlit.order')),
            ],
        ),
        migrations.CreateModel(
            name='Tribunal_Appeal_Final',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_date', models.DateField(verbose_name='Appeal File Date')),
                ('comments', models.TextField(blank=True, max_length=300, verbose_name='Write a message to Advisor')),
                ('upload', models.FileField(upload_to='')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Created On')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Update On')),
                ('app_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_appeal.appellate_order')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idtlit.order')),
            ],
        ),
        migrations.CreateModel(
            name='Tribunal_Appeal_Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True, max_length=300, verbose_name='Pls write Message to location user')),
                ('upload', models.FileField(upload_to='')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Created On')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Update On')),
                ('app_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_appeal.appellate_order')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idtlit.order')),
            ],
        ),
    ]
