# Generated by Django 4.1.7 on 2023-05-07 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribunal_appeal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tribunal_order_details',
            name='demand',
            field=models.PositiveIntegerField(default=0, verbose_name='Balance Demand as per Tribuanl Order'),
        ),
    ]
