# Generated by Django 4.1.7 on 2023-04-15 13:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('advisor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('tax_cat', models.CharField(choices=[('1', 'Indirect Tax'), ('2', 'Direct Tax'), ('3', 'Custom')], default='Indirect Tax', max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='RecentNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsdate', models.DateField(default=datetime.date.today)),
                ('newstext', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=150)),
                ('address', models.TextField(max_length=300)),
                ('city', models.CharField(max_length=70)),
                ('zipcode', models.IntegerField()),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compliance.state')),
            ],
        ),
        migrations.CreateModel(
            name='UserQueryNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_date', models.DateField(default=datetime.date.today)),
                ('tax_cat', models.CharField(choices=[('1', 'Indirect Tax'), ('2', 'Direct Tax'), ('3', 'Custom')], default='Indirect Tax', max_length=70)),
                ('query', models.TextField(default='Pls Explain the transaction in detail', max_length=500)),
                ('upload', models.FileField(default='no file', max_length=254, upload_to='media')),
                ('status', models.CharField(choices=[('open', 'open'), ('replied', 'replied'), ('close', 'close')], default='open', max_length=10)),
                ('query_reply', models.TextField(default='Reply Open', max_length=500)),
                ('act', models.ForeignKey(help_text='Pls Select the Act from drop down', on_delete=django.db.models.deletion.CASCADE, to='compliance.act')),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compliance.advisor')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compliance.unit')),
                ('user', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaxUserClass',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('designation', models.CharField(choices=[('Asst. Manager', 'Asst.Manager'), ('Manager', 'Manager'), ('Senior Manager', 'Senior Manager'), ('AGM', 'AGM'), ('GM', 'GM'), ('AVP', 'AVP'), ('VP', 'VP'), ('EVP', 'EVP')], max_length=75)),
                ('department', models.CharField(choices=[('Finance', 'Finance'), ('Marketing', 'Marketing'), ('HR', 'HR'), ('Sales', 'Sales'), ('Export', 'Export'), ('External Affairs', 'External Affairs'), ('Legal', 'Legal')], max_length=70)),
                ('band', models.CharField(choices=[('1A', '1A'), ('1A', '1A'), ('2A', '2A'), ('2B', '2B'), ('3A', '3A'), ('3B', '3B'), ('4A', '4A'), ('4B', '4B'), ('5A', '5A'), ('5B', '5B'), ('5C', '5C')], max_length=10)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compliance.unit')),
            ],
        ),
        migrations.CreateModel(
            name='TaxNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsdate', models.DateField(default=datetime.date.today)),
                ('newstext', models.TextField(max_length=150)),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compliance.act')),
            ],
        ),
    ]
