# Generated by Django 4.1.7 on 2023-04-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisor',
            name='tax_cat',
            field=models.CharField(choices=[('1', 'Indirect Tax'), ('2', 'Direct Tax'), ('3', 'Custom'), ('4', 'Taxhead')], default='Indirect Tax', max_length=70),
        ),
    ]
