# Generated by Django 4.1.7 on 2023-04-15 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App_Appeal_Hearing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hearing_date', models.DateField()),
                ('was_effective', models.BooleanField(default=False, help_text='Pls upload copy of adjounment letter if not effective')),
                ('hearing_gist', models.TextField(blank=True, help_text='Pls Enter Brief of hearing', max_length=200)),
                ('is_complete', models.BooleanField(default=False)),
                ('next_date', models.DateField(blank=True, help_text='Pls. enter next date if hearing in not complete')),
                ('upload', models.FileField(blank=True, help_text='Pls upload as filed written submission,if filed', upload_to='')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Created On')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Update On')),
            ],
        ),
        migrations.CreateModel(
            name='Appellate_Appeal_Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True, max_length=300, verbose_name='Pls write Message to location user')),
                ('upload', models.FileField(upload_to='')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Created On')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Update On')),
            ],
        ),
        migrations.CreateModel(
            name='Appellate_Appeal_Final',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True, max_length=300, verbose_name='Write a message to Advisor')),
                ('upload', models.FileField(upload_to='')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Created On')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Update On')),
            ],
        ),
        migrations.CreateModel(
            name='Appellate_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(help_text='Pls Enter Order No', max_length=50)),
                ('order_date', models.DateField()),
                ('order_gist', models.TextField(help_text='Pls enter summary of order', max_length=300)),
                ('demand', models.PositiveIntegerField(verbose_name='Impugned balance demand')),
                ('outcome', models.CharField(choices=[('Allowed', 'Allowed'), ('Rejected', 'Rejected'), ('Partly_Allowed', 'Partly Allowed'), ('Remand Back', 'Remand Back')], max_length=50)),
                ('next_appeal_by_date', models.DateField(verbose_name='2nd appeal limitation Date')),
                ('upload', models.FileField(help_text='Pls upload Copy of Order', upload_to='')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Created On')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Update On')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('Pre-Deposit', 'Pre-Deposit'), ('Admitted_Tax', 'Admitted_Tax'), ('DRC-03', 'DRC-03'), ('Interest', 'Interest'), ('Penalty', 'Penalty')], max_length=50)),
                ('challan_no', models.CharField(max_length=50)),
                ('challan_date', models.DateField()),
                ('tax', models.PositiveIntegerField(default=0)),
                ('interest', models.PositiveIntegerField(default=0)),
                ('penalty', models.PositiveIntegerField(default=0)),
                ('upload', models.FileField(upload_to='')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Created On')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Update On')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
