# Generated by Django 4.1.7 on 2023-04-15 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('idtlit', '0001_initial'),
        ('app_appeal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idtlit.order'),
        ),
        migrations.AddField(
            model_name='appellate_order',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appellate_order',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idtlit.order'),
        ),
        migrations.AddField(
            model_name='appellate_appeal_final',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appellate_appeal_final',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idtlit.order'),
        ),
        migrations.AddField(
            model_name='appellate_appeal_draft',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appellate_appeal_draft',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idtlit.order'),
        ),
        migrations.AddField(
            model_name='app_appeal_hearing',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='app_appeal_hearing',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idtlit.order'),
        ),
    ]
