# Generated by Django 4.1.7 on 2023-04-15 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_appeal', '0003_appellate_order_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appellate_Order_Details',
        ),
    ]
