# Generated by Django 4.1.7 on 2023-04-22 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idtlit', '0020_delete_recommend_writ'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_appeal', '0007_appellate_order_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appellate_order_details',
            name='addition',
        ),
        migrations.AddField(
            model_name='appellate_order_details',
            name='demand',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appellate_order_details',
            name='issue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='idtlit.issue'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Hearing_Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_no', models.CharField(max_length=50)),
                ('notice_date', models.DateField()),
                ('hearing_date', models.DateField()),
                ('upload', models.FileField(upload_to='')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Created On')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Update On')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
