# Generated by Django 4.1.7 on 2023-04-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_appeal', '0008_remove_appellate_order_details_addition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appellate_order_details',
            name='is_remanded',
            field=models.BooleanField(default=False),
        ),
    ]
