# Generated by Django 4.1.7 on 2023-04-22 13:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_appeal', '0009_appellate_order_details_is_remanded'),
    ]

    operations = [
        migrations.AddField(
            model_name='appellate_appeal_final',
            name='file_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Appeal File Date'),
            preserve_default=False,
        ),
    ]
