# Generated by Django 4.1.7 on 2023-04-23 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idtlit', '0020_delete_recommend_writ'),
        ('app_appeal', '0010_appellate_appeal_final_file_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='hearing_notice',
            name='order_no',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='idtlit.order'),
            preserve_default=False,
        ),
    ]
