# Generated by Django 4.1.7 on 2023-04-23 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_appeal', '0011_hearing_notice_order_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hearing_notice',
            old_name='order_no',
            new_name='order',
        ),
    ]
