# Generated by Django 4.1.7 on 2023-04-23 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_appeal', '0012_rename_order_no_hearing_notice_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_appeal_hearing',
            name='next_date',
            field=models.DateField(blank=True, help_text='Pls. enter next date if hearing in not complete', null=True),
        ),
        migrations.AlterField(
            model_name='app_appeal_hearing',
            name='upload',
            field=models.FileField(blank=True, help_text='Pls upload as filed written submission,if filed', null=True, upload_to=''),
        ),
    ]
