# Generated by Django 4.1.7 on 2023-04-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_appeal', '0013_alter_app_appeal_hearing_next_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appellate_order_details',
            name='admitted_tax',
            field=models.PositiveIntegerField(default=0, verbose_name='Balance Disputed Tax'),
        ),
    ]
