# Generated by Django 4.1.7 on 2023-04-23 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idtlit', '0020_delete_recommend_writ'),
        ('app_appeal', '0014_appellate_order_details_admitted_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appellate_order_details',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idtlit.order'),
        ),
    ]
