# Generated by Django 4.1.7 on 2023-04-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_appeal', '0015_alter_appellate_order_details_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='appellate_order_details',
            name='reason',
            field=models.TextField(default='Pls give reason of demand', max_length=200, verbose_name='Reason for Demand'),
        ),
    ]
