# Generated by Django 4.1.7 on 2023-04-26 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_appeal', '0016_appellate_order_details_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='appellate_order_details',
            name='app_order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_appeal.appellate_order'),
            preserve_default=False,
        ),
    ]
