# Generated by Django 4.1.7 on 2023-04-29 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_appeal', '0017_appellate_order_details_app_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appellate_order_details',
            options={'ordering': ['issue']},
        ),
    ]
