# Generated by Django 4.1.7 on 2023-04-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_appeal', '0018_alter_appellate_order_details_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='appellate_order_details',
            name='approval_reason',
            field=models.CharField(default='Pls. write approval reason here ', max_length=100),
        ),
        migrations.AddField(
            model_name='appellate_order_details',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appellate_order_details',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appellate_order_details',
            name='reco_reason',
            field=models.CharField(default='Write recommendation reason here', max_length=100),
        ),
    ]
