# Generated by Django 4.1.7 on 2023-05-01 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_appeal', '0019_appellate_order_details_approval_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appellate_order_details',
            name='admitted_tax',
            field=models.PositiveIntegerField(default=0, verbose_name='Admitted Tax'),
        ),
    ]
