# Generated by Django 4.1.7 on 2023-04-15 13:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compliance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Initial_Notice',
            fields=[
                ('proceeding', models.AutoField(primary_key=True, serialize=False)),
                ('proceeding_type', models.CharField(choices=[('Assessment', 'Assessment'), ('Re-Assessment', 'Re-Assessment'), ('Investigation', 'Investigation'), ('search Seizure', 'Search Seizure'), ('Survey', 'Survey'), ('Pre-Show_Cause_Notice', 'Pre-Show_Cause_Notice'), ('Other', 'Other')], max_length=50)),
                ('notice_no', models.CharField(max_length=50)),
                ('notice_date', models.DateField()),
                ('notice_type', models.CharField(choices=[('Initiation Notice', 'Initiation Notice'), ('Scrutiny Notice', 'Scrutiny Notice'), ('Notice Seeking Information', 'Notice Seeking Information'), ('Other Notice', 'Other Notice')], max_length=100)),
                ('year', models.CharField(choices=[('2005-06', '2005-06'), ('2006-07', '2006-07'), ('2007-08', '2007-08'), ('2008-09', '2008-09'), ('2009-10', '2009-10'), ('2010-11', '2010-11'), ('2011-12', '2011-12'), ('2012-13', '2012-13'), ('2013-14', '2013-14'), ('2014-15', '2014-15'), ('2015-16', '2015-16'), ('2016-17', '2016-17'), ('2017-18', '2018-19'), ('2019-20', '2019-20'), ('2020-21', '2020-21'), ('2021-22', '2021-22'), ('2022-23', '2022-23'), ('2023-24', '2023-24'), ('2024-25', '2024-25')], help_text='Pls Enter the Financial Year', max_length=20, verbose_name='Financial Year')),
                ('description', models.TextField(help_text='Pls Enter Gist of Notice', max_length=500, verbose_name='Notice Gist')),
                ('production_of_books', models.BooleanField(default=True, help_text='Pls click if proudction of books and evidence is sought in the notice')),
                ('reply_sought', models.BooleanField(default=True, help_text='Pls click if reply is sought in the notice')),
                ('desired_date_of_reply', models.DateField(blank=True, help_text='Pls leave blank if reply is not sought', null=True)),
                ('appearance_sought', models.BooleanField(default=True, help_text='Pls Click if Authority has sought your appeanrance in the matter')),
                ('date_of_appearance', models.DateField(blank=True, help_text='Pls Enter date of appearance as sought in the Notice', null=True)),
                ('upload', models.FileField(help_text='Pls upload copy of Notice here', upload_to='')),
                ('status', models.CharField(default='Open', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update On')),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compliance.act')),
                ('advisor', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='compliance.advisor')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaxJurisdiction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('adress1', models.CharField(max_length=50)),
                ('adress2', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compliance.unit')),
            ],
        ),
        migrations.CreateModel(
            name='ShowCauseNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scn_no', models.CharField(max_length=50)),
                ('scn_date', models.DateField()),
                ('scn_gist', models.TextField(max_length=200)),
                ('reply_by_date', models.DateField()),
                ('proposed_additions', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('upload', models.FileField(blank=True, help_text='Pls upload SCN', null=True, upload_to='', verbose_name='Upload Documents')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Created On')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Update On')),
                ('created_by', models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('proceeding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idtlit.initial_notice')),
            ],
        ),
        migrations.CreateModel(
            name='ProposedAddition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_addition', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Created On')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Updated On')),
                ('created_by', models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='idtlit.issue')),
                ('proceeding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idtlit.initial_notice')),
                ('scn_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idtlit.showcausenotice')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=100)),
                ('order_date', models.DateField(default=datetime.datetime.today)),
                ('order_gist', models.TextField(max_length=500)),
                ('total_demand', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Impugned Demand')),
                ('appeal_by_date', models.DateField(blank=True, verbose_name='Last date of filing appeal')),
                ('upload', models.FileField(upload_to='', verbose_name='Upload Order')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Created On')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Update On')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('proceeding', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='idtlit.initial_notice')),
                ('scn_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Order', to='idtlit.showcausenotice')),
            ],
        ),
        migrations.CreateModel(
            name='NoticeReplyFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_date', models.DateField(verbose_name='Pls Enter date of Filing reply')),
                ('comment', models.TextField(help_text='Pls enter anything relevant', max_length=100)),
                ('upload', models.FileField(upload_to='', verbose_name='Upload Acknowledged Reply')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update On')),
                ('created_by', models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('proceeding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idtlit.initial_notice')),
                ('scn_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noticereply', to='idtlit.showcausenotice')),
            ],
        ),
        migrations.CreateModel(
            name='NoticeReplyDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True, help_text='Pls enter comments if any', max_length=200, null=True)),
                ('upload', models.FileField(upload_to='', verbose_name='Upload Draft Reply')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update On')),
                ('created_by', models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('proceeding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idtlit.initial_notice')),
                ('scn_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draftreply', to='idtlit.showcausenotice')),
            ],
        ),
        migrations.AddField(
            model_name='initial_notice',
            name='authority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idtlit.taxjurisdiction'),
        ),
        migrations.AddField(
            model_name='initial_notice',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='initial_notice',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compliance.unit'),
        ),
        migrations.CreateModel(
            name='Hearing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hearing_date', models.DateField()),
                ('was_effective', models.BooleanField(default=False, help_text='Pls upload copy of adjounment letter if not effective')),
                ('hearing_gist', models.TextField(blank=True, help_text='Pls Enter Brief of hearing', max_length=200)),
                ('is_complete', models.BooleanField(default=False)),
                ('next_date', models.DateField(blank=True, help_text='Pls. enter next date if hearing in not complete')),
                ('upload', models.FileField(blank=True, help_text='Pls upload as filed written submission,if filed', upload_to='')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Created On')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Update On')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('proceeding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idtlit.initial_notice')),
            ],
        ),
    ]
