# Generated by Django 4.1.7 on 2023-04-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idtlit', '0002_addition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hearing',
            name='next_date',
            field=models.DateField(blank=True, help_text='Pls. enter next date if hearing in not complete', null=True),
        ),
    ]
