# Generated by Django 4.1.7 on 2023-04-15 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_appeal', '0006_delete_appellate_order_details'),
        ('idtlit', '0003_alter_hearing_next_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Addition',
        ),
    ]
