# Generated by Django 4.1.7 on 2023-04-16 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idtlit', '0005_addition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='proceeding',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='idtlit.initial_notice'),
        ),
    ]
