# Generated by Django 4.1.7 on 2023-04-16 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idtlit', '0006_alter_order_proceeding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acutal_Addition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_additions', models.DecimalField(decimal_places=2, max_digits=12)),
                ('admitted_additions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('disputed_additions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_appealed', models.BooleanField(default=False, verbose_name='Whether Appealed')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idtlit.issue')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idtlit.order')),
            ],
        ),
    ]
