# Generated by Django 4.1.7 on 2023-04-16 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idtlit', '0007_acutal_addition'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Acutal_Addition',
            new_name='Actual_Addition',
        ),
    ]
