# Generated by Django 4.1.7 on 2023-04-16 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idtlit', '0008_rename_acutal_addition_actual_addition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addition',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idtlit.issue'),
        ),
        migrations.DeleteModel(
            name='Actual_Addition',
        ),
    ]
