# Generated by Django 4.1.7 on 2023-04-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idtlit', '0009_alter_addition_issue_delete_actual_addition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addition',
            name='admitted_additions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='addition',
            name='disputed_additions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='addition',
            name='total_additions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
