# Generated by Django 4.1.7 on 2023-04-17 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idtlit', '0010_alter_addition_admitted_additions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actual_Addition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_additions', models.PositiveIntegerField(default=0)),
                ('admitted_additions', models.PositiveIntegerField(default=0)),
                ('disputed_additions', models.PositiveIntegerField(default=0)),
                ('is_appealed', models.BooleanField(default=False, verbose_name='Whether Appealed')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idtlit.order')),
            ],
        ),
    ]
