# Generated by Django 4.1.7 on 2023-04-17 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idtlit', '0011_actual_addition'),
    ]

    operations = [
        migrations.AddField(
            model_name='actual_addition',
            name='issue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='idtlit.proposedaddition'),
            preserve_default=False,
        ),
    ]
