# Generated by Django 4.1.7 on 2023-04-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idtlit', '0012_actual_addition_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='actual_addition',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='By checking the appove option you are consenting filing of appeal/payment of admitted tax', verbose_name='Approve'),
        ),
    ]
