# Generated by Django 4.1.7 on 2023-04-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idtlit', '0014_actual_addition_approval_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actual_addition',
            name='approval_reason',
            field=models.CharField(default='Pls give reason for appeal/admiting the tax', help_text='Pls give reason for seeking approval', max_length=200, verbose_name='Reason'),
        ),
    ]
