# Generated by Django 4.1.7 on 2023-04-19 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('idtlit', '0015_alter_actual_addition_approval_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='actual_addition',
            name='approved_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Approver', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actual_addition',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='Created On'),
        ),
        migrations.AddField(
            model_name='actual_addition',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='creatror', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actual_addition',
            name='is_recommended',
            field=models.BooleanField(default=False, help_text='Pls chech the box to recommend the actions', verbose_name='Recommend'),
        ),
        migrations.AddField(
            model_name='actual_addition',
            name='recommended_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Recommender', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actual_addition',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Update On'),
            preserve_default=False,
        ),
    ]
