# Generated by Django 4.1.7 on 2023-04-19 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('idtlit', '0016_actual_addition_approved_by_actual_addition_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addition',
            name='approval_reason',
            field=models.CharField(default='Pls give reason for appeal/admiting the tax', help_text='Pls give reason for seeking approval', max_length=200, verbose_name='Reason'),
        ),
        migrations.AddField(
            model_name='addition',
            name='approved_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Approver', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addition',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='Created On'),
        ),
        migrations.AddField(
            model_name='addition',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='creatror', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addition',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='By checking the appove option you are consenting filing of appeal/payment of admitted tax', verbose_name='Approve'),
        ),
        migrations.AddField(
            model_name='addition',
            name='is_recommended',
            field=models.BooleanField(default=False, help_text='Pls chech the box to recommend the actions', verbose_name='Recommend'),
        ),
        migrations.AddField(
            model_name='addition',
            name='recommended_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Recommender', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addition',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Update On'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Actual_Addition',
        ),
    ]
