# Generated by Django 4.1.7 on 2023-04-19 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('idtlit', '0017_addition_approval_reason_addition_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addition',
            name='approval_reason',
            field=models.CharField(default='Pls give reason for appeal/admiting the tax', max_length=200, verbose_name='Reason'),
        ),
        migrations.AlterField(
            model_name='addition',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Approver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='addition',
            name='recommended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Recommender', to=settings.AUTH_USER_MODEL),
        ),
    ]
