# Generated by Django 4.1.7 on 2023-04-21 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compliance', '0002_alter_advisor_tax_cat'),
        ('idtlit', '0018_alter_addition_approval_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='recommend_writ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Pls explain the reasons for filing writ in 500 words max', max_length=500, verbose_name='Writ Justification')),
                ('is_recommended', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('approver_comment', models.TextField(blank=True, max_length=300, null=True)),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Created On')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Update On')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intiator', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='idtlit.order')),
                ('recommended_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommender', to='compliance.advisor')),
            ],
        ),
    ]
