# Generated by Django 4.1.7 on 2023-04-29 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idtlit', '0020_delete_recommend_writ'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['id']},
        ),
    ]
