# Generated by Django 4.1.7 on 2023-05-09 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idtlit', '0021_alter_issue_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='initial_notice',
            options={'ordering': ['created']},
        ),
    ]
